[15.0][4020][ADD] partner_edit_restrict
qrtl/rmm-custom pull request #109
Opened 2023-11-27 04:53 UTC by AungKoKoLin1997

[4020](https://www.quartile.co/web#id=4020&cids=3&model=project.task&view_type=form)

2023-11-27 05:35 UTC, yostashiro commented
@AungKoKoLin1997 Can you follow up on the test error please.

2023-11-30 03:47 UTC, kanda999 requested changes
Get an error when normal user try to create a purchase order as a vendor with a partner whose changes are restricted (`restrict_edit=True`). Can you please confirm this?

![2023-11-30_12h43_28](https://github.com/qrtl/rmm-custom/assets/101688144/e5a096cc-963b-434d-b319-c3a1bf5574c1)

2023-11-30 09:35 UTC, kanda999 approved these changes
Functional test

2023-11-30 09:44 UTC, kanda999 requested changes
I found typo

2023-11-30 09:44 UTC, kanda999 commented on partner_edit_restrict/models/res_partner.py
> +                raise UserError(_("You are not allowed to modify this parnter record."))
```suggestion
                raise UserError(_("You are not allowed to modify this partner record."))
```

2023-11-30 09:58 UTC, kanda999 approved these changes

2023-12-06 08:18 UTC, merged