[4253][15.0][MIG] stock_quant_list_view: Migration to 15.0
qrtl/rmm-custom pull request #112
Opened 2024-01-23 03:49 UTC by AungKoKoLin1997

[4253](https://www.quartile.co/web#cids=3&menu_id=505&action=1457&model=project.task&view_type=form&id=4253)

2024-01-25 14:13 UTC, yostashiro reviewed
@kanda999 Can you double-check if we need to keep this module?

2024-02-01 08:18 UTC, kanda999 requested changes
@AungKoKoLin1997 
The customer needed this view and decided to leave this moudle.

2024-02-01 08:18 UTC, kanda999 commented on stock_quant_list_view/views/stock_quant_views.xml
> +                <field name="product_id" />
```suggestion
                <field name="product_id" optinal="show" />
```
Can you please add optional?

2024-02-02 03:10 UTC, kanda999 approved these changes
Code and Functional review

2024-02-02 03:41 UTC, merged