[3929][ADD] restful
qrtl/rmm-custom pull request #117
Opened 2024-02-07 05:09 UTC by AungKoKoLin1997

[3929](https://www.quartile.co/web#id=3929&cids=3&menu_id=505&action=1457&model=project.task&view_type=form)

2024-07-25 14:19 UTC, yostashiro commented on restful/controllers/main.py
> +                data = {"id": resource.id}
For this particular case, I do not feel very comfortable with simply overriding the code.  Can we instead comment out the original line, and state the reason of the change, marking it as our local fix.

2024-07-29 05:00 UTC, yostashiro requested changes
@AungKoKoLin1997 Please organize the commits, with the first commit untouched from the original code, assigning proper commit messages.

2024-08-01 09:24 UTC, kanda999 approved these changes
Functional review.

2024-08-01 09:37 UTC, yostashiro approved these changes

2024-08-06 02:13 UTC, merged