st1 [2495][ADD] product_archive_sold_product
qrtl/rmm-custom pull request #13
Opened 2022-08-02 01:48 UTC by kanda999

[2495](https://www.quartile.co/web?#id=2495&action=771&model=project.task&view_type=form&menu_id=505)

A cron task that will "Archive" products which have met certain conditions(qty_delivered > 0)

2022-08-02 05:17 UTC, yostashiro requested changes

2022-08-02 05:17 UTC, yostashiro commented on product_archive_sold_product/models/product_product.py
> +                product_id
```suggestion
            SELECT
                sol.product_id
            FROM
                sale_order_line sol
            JOIN
                product_product pp ON sold.product_id = pp.id
            WHERE
                sol.state in ('sale', 'done')
                AND sol.qty_delivered > 0
                AND pp.active = True
            GROUP BY
                sol.product_id
```

2022-08-02 05:17 UTC, yostashiro commented on product_archive_sold_product/models/product_product.py
> +            sale_vals[dictionaly["product_id"]] = dictionaly["sale_qty"]
```suggestion
        prod_ids = [r[0] for r in self.env.cr.fetchall()]
```
`prod_ids = self.env.cr.fetchall()` might just work as well, but I don't feel comfortable with throwing a list of tuples in `browse()`.

2022-08-02 05:17 UTC, yostashiro commented on product_archive_sold_product/models/product_product.py
> +                prod.product_tmpl_id.write({"active": False})
```suggestion
        for prod in self.browse(prod_ids):
            # if product has reordering rules then deactivate first
            if prod.orderpoint_ids:
                prod.orderpoint_ids.write({"active": False})
            prod.product_tmpl_id.write({"active": False})
```

2022-08-03 15:38 UTC, yostashiro requested changes
We might also need to consider the chunk size depending on the performance on data with large volume (in a similar manner as https://github.com/qrtl/hls-oca/pull/22).

2022-08-03 15:38 UTC, yostashiro commented on product_archive_sold_product/models/product_product.py
> +                AND (pt.type = 'product' OR pt.type = 'consu')
```suggestion
                AND pt.type in ('product', 'consu')
```

2022-08-03 15:38 UTC, yostashiro commented on product_archive_sold_product/readme/DESCRIPTION.rst
> +  - Target products to "Archive": The product has to be a stockable or consumable product and (qty_delivered > 0)
```suggestion
This module provides the function to archive "sold" products with cron.

Assumptions:

* Physical products (stockable/consumable) are created per piece with no exceptions. 
* Product variant feature is not enabled (i.e. there is just one variant per template).
```

2022-08-03 15:38 UTC, yostashiro commented on product_archive_sold_product/__manifest__.py
> +    "depends": ["sale"],
```suggestion
    "depends": ["sale_stock"],
```
Not strictly a technical dependency, but product type `product` comes from stock module.

2022-08-04 01:14 UTC, kanda999 commented
I've successfully archived 2691 products in the development environment.

2022-08-04 01:19 UTC, yostashiro approved these changes
👍

2022-08-04 01:22 UTC, merged