[4846][ADD] product_arcchive_purchase_order_cancel
qrtl/rmm-custom pull request #145
Opened 2024-09-19 16:05 UTC by AungKoKoLin1997

[4846](https://www.quartile.co/web#id=4846&cids=3&model=project.task&view_type=form)

2024-09-20 06:08 UTC, yostashiro reviewed
Would it make more sense to extend the write() method of purchase.order to do the archive? We can also revive the product when the state is reset to draft. I prefer not to add a cron when it's not necessary. @kanda999 What do you think?

We can use the current code to clean up the existing records in post_init_hook.

2024-09-20 06:11 UTC, yostashiro commented
> Would it make more sense to extend the write() method of purchase.order to do the archive? We can also revive the product when the state is reset to draft. I prefer not to add a cron when it's not necessary. @kanda999 What do you think?

In case we go for this, I suggest the module name to be purchase_cancel_product_archive.

2024-09-26 10:08 UTC, kanda999 commented
@AungKoKoLin1997 
Would you consider yoshi-san's suggestion?　There is no need to do this process in cron.
Archives the product when the purchase.order is canceled, and unarchives it when it is reversed to a quote.

2024-09-26 10:22 UTC, AungKoKoLin1997 commented
> @AungKoKoLin1997 Would you consider yoshi-san's suggestion?　There is no need to do this process in cron. Archives the product when the purchase.order is canceled, and unarchives it when it is reversed to a quote.

I agree. Lets go with yoshi's suggestion.

2024-09-26 13:13 UTC, yostashiro requested changes

2024-09-26 13:13 UTC, yostashiro commented on purchase_cancel_product_archive/models/purchase_order.py
> +                products.mapped("product_tmpl_id").write({"active": False})
The logic looks incorrect/suboptimal.  I suggest you extend `button_cancel()` and `button_draft()` instead.

2024-09-27 04:25 UTC, yostashiro commented on purchase_cancel_product_archive/hooks.py
> +    products = cancel_pos.mapped("order_line.product_id")
Just to add some precaution; there could be some rare situations where a PO is cancelled but the same product is used in another PO. Haven't checked if such case actually exists.
```suggestion
    products = cancel_pos.mapped("order_line.product_id")
    products = products.filtered(lambda x: x.quantity_available <= 0.0)
```

2024-09-27 08:53 UTC, yostashiro approved these changes

2024-10-15 05:10 UTC, kanda999 approved these changes

2024-10-15 05:10 UTC, merged