[2946][ADD] sale_commission_seller_agent
qrtl/rmm-custom pull request #35
Opened 2022-11-16 02:25 UTC by AungKoKoLin1997

[2946](https://www.quartile.co/web#id=2946&action=771&model=project.task&view_type=form&menu_id=505)

2022-11-16 02:48 UTC, yostashiro approved these changes
@kanda999 Please review the function and install the module in the test database.

2022-11-16 02:48 UTC, yostashiro commented on sale_commission_seller_agent/models/sale_order_line.py
> +                    ]
```suggestion
            if record.commission_free:
                continue
            # propose the seller of the product in agent line
            if record.product_id.seller_id and record.product_id.seller_id.agent:
                record.agent_ids = [
                    (0, 0, record._prepare_agent_vals(record.product_id.seller_id))
                ]
```

Just to reduce the if ladder.  A minor preference.

2022-11-16 05:09 UTC, yostashiro requested changes
Now you broke the logic. :(

2022-11-16 05:09 UTC, yostashiro commented on sale_commission_seller_agent/models/sale_order_line.py
> +            if not record.commission_free:
```suggestion
            if record.commission_free:
```

2022-11-16 05:33 UTC, yostashiro approved these changes

2022-11-16 07:10 UTC, kanda999 approved these changes
Function review. It worked as expected.

2022-12-07 06:27 UTC, kanda999 commented
We need requirement.txt for this PR, but followed by https://github.com/qrtl/rmm-custom/pull/36
The latest commit is for using the gitaggregator.

2022-12-30 09:41 UTC, yostashiro commented
@AungKoKoLin1997 Please rebase your branch and force-push.

2022-12-30 09:47 UTC, AungKoKoLin1997 commented
> @AungKoKoLin1997 Please rebase your branch and force-push.

Done.

2022-12-30 10:17 UTC, yostashiro commented
@kanda999 Please go ahead and merge this at your convenience.

2022-12-30 10:23 UTC, merged