[2971][ADD] hide_invoice_regenerate_agents_button
qrtl/rmm-custom pull request #36
Opened 2022-11-21 04:17 UTC by AungKoKoLin1997

[2971](https://www.quartile.co/web#view_type=form&model=project.task&id=2971&active_id=2971&menu_id=)

2022-11-21 04:28 UTC, yostashiro reviewed
Sorry to be rather pedantic. Can we please rename the module to account_move_hide_regenerate_agents_button.

2022-11-21 04:34 UTC, AungKoKoLin1997 commented
> Sorry to be rather pedantic. Can we please rename the module to account_move_hide_regenerate_agents_button.

@yostashiro After communication with kanda san, this module should be for sale and invoice. So, I added the sale order part and change module name to "hide_regenerate_agents_button"

2022-11-21 04:55 UTC, yostashiro commented
@AungKoKoLin1997 Thanks, yes that makes sense.  Could we then make it `commission_disable_regenerate_agent`, so that the correlation to the commission modules is clearer.

2022-11-21 06:32 UTC, kanda999 approved these changes
Function review.

2022-11-21 06:44 UTC, yostashiro requested changes
@AungKoKoLin1997 Please add test-requirements.txt for the CI.

2022-11-21 06:44 UTC, yostashiro commented on commission_disable_regenerate_agent/views/account_invoice_views.xml
> +    </record>
Please put this record in a separate file (sale_order_views.xml).

2022-11-22 15:03 UTC, yostashiro commented
@AungKoKoLin1997 @kanda999 Please review and adjust this PR as necessary once https://github.com/OCA/commission/pull/387 is merged.

2022-12-27 09:51 UTC, AungKoKoLin1997 commented
We don't need to adjust this PR. This PR is also compatible with latest commission modules

2022-12-27 15:12 UTC, yostashiro approved these changes

2022-12-27 15:20 UTC, yostashiro commented
@kanda999 Let's go ahead and merge https://github.com/qrtl/rmm-oca/pull/15.

@AungKoKoLin1997 Please rebase the feature branch and force-push once the above PR is merged (just to run tests).

2022-12-28 10:01 UTC, yostashiro commented
@kanda999 Let's go ahead and merge this.

2022-12-28 10:06 UTC, merged