[15.0][MIG]account_invoice_delivered_amount
qrtl/rmm-custom pull request #58
Opened 2023-02-02 11:16 UTC by AungKoKoLin1997

[3173](https://www.quartile.co/web#view_type=form&model=project.task&id=3173&active_id=3173&menu_id=)

2023-02-03 05:01 UTC, kanda999 requested changes

2023-02-03 05:01 UTC, kanda999 commented on account_move_delivered_amount/models/account_move_line.py
> +                    taxes["total_excluded"] if taxes else qty_delivered * price
@AungKoKoLin1997 
Incorrect value is entered in Credit Note.  Could you please add sign like account_move?

![2023-02-03_13h55_21](https://user-images.githubusercontent.com/101688144/216516293-1e83c3f5-2b66-485b-9a87-af45e54c795a.png)
![2023-02-03_13h55_50](https://user-images.githubusercontent.com/101688144/216515957-21c2fcf1-0fee-49fb-9425-85412e2b2df8.png)

2023-02-03 06:42 UTC, kanda999 commented on account_move_delivered_amount/models/account_move_line.py
> +                    taxes["total_excluded"] if taxes else qty_delivered * price
Sorry I must have made some mistake. Credit note fucntion is good.

2023-02-03 06:42 UTC, kanda999 approved these changes
Function review.

2023-02-04 10:12 UTC, yostashiro approved these changes

2023-02-06 03:26 UTC, merged