[15.0][3917][IMP] purchase_order_supplier_phone: add functionals from sst
qrtl/rmm-custom pull request #94
Opened 2023-10-25 10:08 UTC by AungKoKoLin1997

[3917](https://www.quartile.co/web#id=3917&cids=3&menu_id=505&action=1457&model=project.task&view_type=form)

2024-01-22 06:53 UTC, kanda999 requested changes

2024-01-22 06:53 UTC, kanda999 commented on purchase_order_supplier_phone/models/purchase_order.py
> +                if self.is_default_partner(partner_id) and (
`is_default_partner` depends on purchase_ext_sst module.

2024-01-23 02:22 UTC, yostashiro commented on purchase_order_supplier_phone/__manifest__.py
> +    "depends": ["purchase_ext_sst"],
To make the reason of dependency clear.
```suggestion
    "depends": [
        "purchase_ext_sst",  # is_default_partner()
    ],
```

2024-01-23 05:28 UTC, kanda999 commented
@AungKoKoLin1997 
Could you please update the readme file?

2024-01-23 07:32 UTC, kanda999 approved these changes

2024-01-29 09:00 UTC, merged