[15.0][3902][MIG] product_ext_sst: Migration to 15.0
qrtl/rmm-custom pull request #97
Opened 2023-10-27 05:06 UTC by AungKoKoLin1997

[3902](https://www.quartile.co/web#id=3902&cids=3&menu_id=505&action=1457&model=project.task&view_type=form)

2024-01-23 08:00 UTC, kanda999 requested changes

2024-01-23 08:00 UTC, kanda999 commented on product_ext_sst/views/product_template_views.xml
> +                <!-- <field name="yahoo_product_state_id" /> -->
```suggestion
                <field name="yahoo_product_state_id" />
```
Why did you comment out?

2024-01-23 08:00 UTC, kanda999 commented on product_ext_sst/views/product_template_views.xml
> +                <field name="sequence" widget="handle" />
```suggestion
                <field name="sequence" widget="handle" optional="show"/>
```
Can you add `optional="show"` to the fields in the tree view?

2024-01-23 08:19 UTC, AungKoKoLin1997 commented on product_ext_sst/views/product_template_views.xml
> +                <!-- <field name="yahoo_product_state_id" /> -->
I create this PR before we add yahoo_product_state_id in product_yahoo_auction_sst.

2024-02-01 07:41 UTC, kanda999 approved these changes
Code and functional review.

2024-02-01 07:42 UTC, merged